# Generated by Django 5.2.7 on 2025-10-12 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('user', 'user'), ('admin', 'admin'), ('editor', 'editor'), ('superuser', 'superuser')], default='user', max_length=10)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=150)),
                ('address', models.CharField(max_length=250)),
                ('country_code', models.CharField(choices=[('Uzb', '+998'), ('Rus', '+7'), ('Usa', '+1'), ('UK', '+44')], default='+998', max_length=10)),
                ('phone', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
