# Generated by Django 5.2.7 on 2025-10-16 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='images.png', null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='country_code',
            field=models.CharField(choices=[('Afghanistan', '+93'), ('Albania', '+355'), ('Algeria', '+213'), ('Argentina', '+54'), ('Armenia', '+374'), ('Australia', '+61'), ('Austria', '+43'), ('Azerbaijan', '+994'), ('Bangladesh', '+880'), ('Belarus', '+375'), ('Belgium', '+32'), ('Brazil', '+55'), ('Bulgaria', '+359'), ('Canada', '+1'), ('China', '+86'), ('Czech Republic', '+420'), ('Denmark', '+45'), ('Egypt', '+20'), ('Finland', '+358'), ('France', '+33'), ('Germany', '+49'), ('Greece', '+30'), ('Hungary', '+36'), ('India', '+91'), ('Indonesia', '+62'), ('Iran', '+98'), ('Iraq', '+964'), ('Ireland', '+353'), ('Italy', '+39'), ('Japan', '+81'), ('Kazakhstan', '+7'), ('Kyrgyzstan', '+996'), ('South Korea', '+82'), ('Malaysia', '+60'), ('Mexico', '+52'), ('Netherlands', '+31'), ('Norway', '+47'), ('Pakistan', '+92'), ('Philippines', '+63'), ('Poland', '+48'), ('Portugal', '+351'), ('Qatar', '+974'), ('Romania', '+40'), ('Russia', '+7'), ('Saudi Arabia', '+966'), ('Singapore', '+65'), ('South Africa', '+27'), ('Spain', '+34'), ('Sweden', '+46'), ('Switzerland', '+41'), ('Turkey', '+90'), ('Turkmenistan', '+993'), ('Ukraine', '+380'), ('United Arab Emirates', '+971'), ('United Kingdom', '+44'), ('United States', '+1'), ('Uzbekistan', '+998')], default='Uzb', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
