# Generated by Django 5.2.7 on 2025-10-13 09:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blogcategory_options_blogcategory_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='link',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
