# Generated by Django 5.2.7 on 2025-10-13 11:31

import blog.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userprofile_user'),
        ('blog', '0005_alter_blog_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='link',
            field=models.CharField(db_index=True, default=blog.models.short_uuid, editable=False, unique=True),
        ),
        migrations.CreateModel(
            name='BlogLikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile')),
            ],
            options={
                'unique_together': {('blog', 'user')},
            },
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
